### ISSUE TITLE
Error while searching Book

### ISSUE THREAD

**Issue by Elektri** [616b2f/Athene#13]
Error while searching in:  http://localhost:5000/Librarian/Books

<img width="650" alt="bildschirmfoto 2017-03-12 um 13 46 03" src="https://cloud.githubusercontent.com/assets/25556032/23831908/8cb1927e-072a-11e7-9adb-245e9c1394aa.png">

**Comment by 616b2f** [comment]
@Elektri try to remove database file in (bin/Debug/netcoreapp1.1/Inventory.Web.db) and run it again.
